apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paw-dev
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  labels:
    gitops.tier.layer: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: applications
  source:
    repoURL: https://github.com/Client-Engineering-Industry-Squad-1/iacs-multi-tenancy-gitops-apps.git
    path: paw/chart
    helm:
      parameters:
      - name: docker_registry_prefix
        value: image-registry.openshift-image-registry.svc:5000/dev
      - name: ingress.host
        value: dev.ibmpeppa.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true